### ISSUE TITLE
feature: option to disable lsp

### ISSUE THREAD

**Issue by zhengpd** [gregorias/coerce.nvim#12]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

Coercing with LSP would be slow somethings. I'd like to disable LSP and use `transform_local` only.

### Describe the solution you'd like

An option like `enable_lsp = false`.

### Describe alternatives you've considered

None.

**Comment by gregorias** [comment]
Thanks for reporting.

You can have the requested behavior using existing configuration options. I’ve described the exact process in [the README](https://github.com/gregorias/coerce.nvim?tab=readme-ov-file#selectively-disabling-lsp-rename).

Since you can have what you want already with the existing interface and not too much work, I prefer not to add knob I have to maintain.

**Comment by zhengpd** [comment]
@gregorias Thank you for the configuration example.
