### ISSUE TITLE
feature: Allow for easily disabling certain modes

### ISSUE THREAD

**Issue by primeapple** [gregorias/coerce.nvim#9]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

While I like the plugin, I don't like the configuration so far.

I don't think `gc` is a good default mapping for either `n` nor `x` mode. They conflict heavily with the command for comments. I can't think of any other good prefix right now, I have it set to `gC` so that it at least doesn't break anything.

It would be easier for me to just disable them. However that's it's not that easy right now, one would need to import the default modes and remove the last two. That might work now but I'm unsure if this works in the future. (BTW, I think the documentation is wrong here, the `self` in `modes = require"coerce".get_default_modes(self.keymap_prefixes),` looks wrong)

### Describe the solution you'd like

Maybe let me set the unwanted mode prefixes to `nil`, like this:

```lua
  default_mode_keymap_prefixes = {
    normal_mode = nil,
    motion_mode = nil,
    visual_mode = nil,
  },
```

Also if you have any reasonable alternatives to `gc` that would help as well.

### Describe alternatives you've considered

Thanks so much for the plugin :)

**Comment by gregorias** [comment]
Hi, thanks for the report.

I don’t have a better operator prefix than `gcr`. Sure it’s a conflict, but is it bad? AFAIK, it only adds a delay if you want to see movement hints after typing `gc`, which I don’t think happens often.

I intend to add a config option for disabling default modes. I’ll not use the keymap prefix option, because it’d be a naming anti-pattern.

I will fix the README, thanks.
